// Code generated by "stringer -type=Rank -linecomment"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-1]
	_ = x[Rank2-2]
	_ = x[Rank3-3]
	_ = x[Rank4-4]
	_ = x[Rank5-5]
	_ = x[Rank6-6]
	_ = x[Rank7-7]
	_ = x[Rank8-8]
	_ = x[Rank9-9]
	_ = x[Rank10-10]
	_ = x[Jack-11]
	_ = x[Queen-12]
	_ = x[King-13]
}

const _Rank_name = "ACE2345678910JACKQUEENKING"

var _Rank_index = [...]uint8{0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 17, 22, 26}

func (i Rank) String() string {
	i -= 1
	if i < 0 || i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
