// Code generated by "stringer -type=Suit -linecomment"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spades-1]
	_ = x[Diamonds-2]
	_ = x[Clubs-3]
	_ = x[Hearts-4]
}

const _Suit_name = "SPADESDIAMONDSCLUBSHEARTS"

var _Suit_index = [...]uint8{0, 6, 14, 19, 25}

func (i Suit) String() string {
	i -= 1
	if i < 0 || i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
